### ISSUE TITLE
Cenário A está parcial, É muito fácil destravar a tela (apenas clicar um botão). 

### ISSUE THREAD

**Issue by eduardomarossi** [mariaeduardabicalho/APS2_Embarcada#14]
Do jeito que está, uma criança poderia facilmente apertar o botão e desconfigurar a máquina.

O ideal seria algum outro recurso (do pior para o melhor):
- Segurar o botão
- Apertar o botão 3 vezes ou mais (pra destravar)
- Apertar dois botões ao mesmo tempo
- Padrão na tela
- Senha na tela

**Comment by manucirne** [comment]
Modifiquei, mas não tá muito estável...
O códico tá certo. Acho que, mesmo com debounce, o botão tá considerando que foi pressionado mais de uma vez quando aperto uma vez só.
